### ISSUE TITLE
class_map: Error in as.double(y) :    cannot coerce type 'S4' to vector of type 'double'

### ISSUE THREAD

**Issue by jmsammy** [AGAuffret/HistMapR#2]
Hello, I've been trying to use this package to convert highlighted areas of maps taken from papers into shapes that I can calculate areas from, for a meta analysis. When I try to use the class_map function, I get the error "Error in as.double(y) :  cannot coerce type 'S4' to vector of type 'double'" - this happens when using my own data, but also happens when using the data in the examples. As far as I can tell, some of these issues come from packages being out of date with each other. What version of R was this package originally built under? I'm hoping that using the package in the correct version of R will help my issue.

**Comment by gakindler** [comment]
Hi @AGAuffret and @jmsammy, I've landed on the same issue. Did something happen to come from either of your efforts?

**Comment by arielolafsalgado** [comment]
Hello! First of all thanks a lot for the initiative. I've the same problems listed before. Have any of you came to any solutions for this problem?

**Comment by AGAuffret** [comment]
Dear all,
Thanks for your interest in using the package. I'm sorry that I didn't see @jmsammy 's post from January, but at least now I seem to be getting the notifications. I will look at this today, hopefully sort it this week. Will post updates and questions here.
/Ali

**Comment by AGAuffret** [comment]
Hello again. I think that the problem should be solved now.

It did seem to be something that happened between R v3 and v4 - when plotting the by-category rasters during the testing phase of class_map (i.e. plot.raster=TRUE). In R v4, when working from within the function, the plotting process threw up the error you mentioned, but this was fixed when I replaced plot() with raster::plot(). 

Annoyingly (for me trying to fix the error, maybe for you too), it worked fine when running the function code line by line, but this meant that initially I thought that it was the return() part of the function that was playing up. When looking at this, I realised that I didn't really need to return anything from the function as it was, because my workflow had been testing through plotting and then saving the raster. It occurred to me that it might be useful to return the classified raster into the workspace, so now I have also added an argument return.raster in the class_map() function. If you set it to TRUE, and assign your class_map line to an object, you can work directly with the raster, should you want to.

Anyway, it would be great if one or more of you could re-install and test the package to see if it works for you. If so, let me know and I can close the issue. I have tested it on v. 4.0.3 (Windows) and 3.4.4 (Ubuntu).

Ali
